//
// Macros.swift
//
// TigaseSQLite3.swift
// Copyright (C) 2020 "Tigase, Inc." <office@tigase.com>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License,
// or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. Look for COPYING file in the top folder.
// If not, see http://www.gnu.org/licenses/.
//
//

import Foundation

@attached(conformance)
@attached(member, names: named(`init`), named(`fields`), named(`FieldTypes`), named(`loadRelations`), named(`relationTables`), named(`insert`), named(`delete`))
public macro Entity() = #externalMacro(module: "TigaseSQLite3Macros", type: "EntityMacro")
@attached(peer)
public macro Column(_: String? = nil) = #externalMacro(module: "TigaseSQLite3Macros", type: "ColumnMacro")
@attached(peer)
public macro Relation(_: String) = #externalMacro(module: "TigaseSQLite3Macros", type: "RelationMacro")
@attached(peer)
public macro Autogenerated() = #externalMacro(module: "TigaseSQLite3Macros", type: "AutogeneratedMacro")
@attached(peer)
public macro PrimaryKey() = #externalMacro(module: "TigaseSQLite3Macros", type: "PrimaryKeyMacro")

@freestanding(expression)
public macro Update<T: SQLCodable>(_: (T)->Void) -> [ModelUpdateExpression<T>] = #externalMacro(module: "TigaseSQLite3Macros", type: "UpdateMacro")

@freestanding(expression)
public macro Query<T:SQLCodable>(_: (T)->Bool) -> ModelQueryExpression<T> = #externalMacro(module: "TigaseSQLite3Macros", type: "QueryMacro")
